language: android
jdk: oraclejdk7

android:
  components:
    - android-21
    - build-tools-21.1.2
    - extra-android-m2repository

branches:
  only:
    - mmathieum

before_install:
 - chmod +x gradlew

script: ./gradlew -c settings.gradle.travis build

after_success:
  - coveralls
