language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.1.2
    - android-21

branches:
  only:
    - mmathieum

before_install:
 - chmod +x gradlew

script: ./gradlew -c settings.gradle.travis build
